version: "3"

services:
  pg:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      PGDATA: /PostgresStorage/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/PostgresStorage/data/pgdata

volumes:
  db-data: